name: funny_movies_workflow
on: [pull_request]

jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:12.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: "funny_movies_test"
          POSTGRES_PASSWORD: ""
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: |
          echo "RAILS_ENV=test" >> $GITHUB_ENV
      - name: Check timezone
        run: |
          sudo ln -f -s /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime
          timedatectl
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle config --local build.sassc --disable-march-tune-native
          bundle install --jobs 4 --retry 3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install packages
        run: |
          yarn install --pure-lockfile
      - name: Setup test database
        run: |
          bin/rails db:create
          bin/rails db:migrate
      - name: Compile assets
        run: |
          bin/rails assets:precompile
      - name: Run tests
        run: |
          bin/rails test
